server:
  port: 9568

spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

# 项目相关配置
upload:
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/equ/transfer/uploadPath，Linux配置 /root/apps/uploadPath）
  profile: D:/uploadPath/
  # 获取ip地址开关
  addressEnabled: false